### ISSUE TITLE
Travis 2.x broken

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/travis#59]
Probably due to https://github.com/FriendsOfCake/travis/blob/master/before_script.sh#L16
it cannot find anything anymore

So
```
  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
```
does not work anymore. We currently don't have 2.x coverage anymore.

Example: https://travis-ci.org/dereuromark/cakephp-shim/builds/57485886

**Comment by beporter** [comment]
The tagging is not the problem, actually. I spent most of Friday with @jtyost2 trying to troubleshoot this and we spent a lot of time pursing that same line of thinking, but it turns out the issue is actually Github rate limiting.

```shell
++latest_ref
+++curl --silent https://raw.github.com/cakephp/cakephp/master/lib/Cake/VERSION.txt
++MASTER=
+++grep -Ei '^2.6.3\.'
+++tail -1
+++echo ''
++MASTER=
++'[' -n '' ']'
+++curl --silent https://api.github.com/repos/cakephp/cakephp/git/refs/heads
++BRANCH='{
  "message": "API rate limit exceeded for 54.172.141.90. (But here'\''s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}'
```

See this build for an example that has `set -x` for `before_script.sh` turned on: https://travis-ci.org/loadsys/CakePHP-Stateless-Auth/builds/58268566

I'm pretty sure the solution is to just make sure a Github token is set in your travis build first, which as I'm sure you know can be done using an encrypted Travis environment variable. The `before_script.sh` would have to be updated to provide the token during the `curl` commands too, which complicates things a bit.

**Comment by beporter** [comment]
For the time being, I've adjusted our `.travis.yml` file:

* Include a limited-access github auth token as an encrypted env var. ([ref](https://github.com/loadsys/CakePHP-Stateless-Auth/blob/1920d2bfe14e6533bb7bb199e8bbdadaf009fba3/.travis.yml#L13))

    ```yaml
    env:
        global:
            - secure: "abcdef"  # Generated using,
              # `travis encrypt 'GITHUB_TOKEN=your_read_only_public_repos_only_token_here'`
    ```

* Include a `sed` command to inject the token into the `curl` requests. ([ref](https://github.com/loadsys/CakePHP-Stateless-Auth/blob/1920d2bfe14e6533bb7bb199e8bbdadaf009fba3/.travis.yml#L44))

    ```yaml
    install:
        - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
        - 'sed -i'''' ''s|curl |curl -H "Authorization: token \$GITHUB_TOKEN" |g'' ../travis/before_script.sh'
    ```

Resulting build: https://travis-ci.org/loadsys/CakePHP-Stateless-Auth/builds/58278071

**Comment by dereuromark** [comment]
Do we have a less workaround solution for this yet for 2.x?

**Comment by beporter** [comment]
One option might be to clone the _entire_ `cakephp/cakephp` repo earlier in the process and search for the tags/branches **locally** in git instead of via curl calls to Github's API...
